# Generated by Django 4.1.4 on 2022-12-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_book_description_book_is_published_book_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, upload_to='covers/'),
        ),
    ]
