# Generated by Django 4.1.4 on 2022-12-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='firstname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='author',
            name='lastname',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
