# Generated by Django 4.1.4 on 2022-12-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_author_firstname_author_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='demo.book'),
        ),
    ]
